
yolov7: {
  opt0: {
    weights: '''''',
    cfg: ./yolov7/cfg/training/yolov7.yaml,
    data: /home/pedro/Documentos/Dev/IC/deteccao_objetos/Mask-Wearing-19-YOLOv7/data.yaml,
    hyp: ./yolov7/data/hyp.scratch.p5.yaml,
    epochs: 1,
    batch-size: 1
  },
  opt1: {
    weights: '''''',
    cfg: ./yolov7/cfg/training/yolov7.yaml,
    data: /home/pedro/Documentos/Dev/IC/deteccao_objetos/Mask-Wearing-19-YOLOv7/data.yaml,
    hyp: ./yolov7/data/hyp.scratch.p5.yaml,
    epochs: 100,
    batch-size: 15
  },
  opt2: {
    weights: '''''',
    cfg: ./yolov7/cfg/training/yolov7.yaml,
    data: /home/pedro/Documentos/Dev/IC/deteccao_objetos/Mask-Wearing-19-YOLOv7/data.yaml,
    hyp: ./yolov7/data/hyp.scratch.p5.yaml,
    epochs: 200,
    batch-size: 15
  }
}
yolov6: {
  opt0: {
    bacth-size: 15,
    epochs: 100,
    conf: ./yolov6/configs/yolov6m.py,
    data: ./Mask-Wearing-19-YOLOv6,
    fuse_ab: True,
    device: 0
  }
}